"""All api endpoints related to account details."""
ACCOUNT_PREFIX = "/account"
ACCOUNT_ROOT = "/"
ACCOUNT_ADD_USER = "/add-user"
ACCOUNT_LOGIN = "/login"
ACCOUNT_LOGOUT = "/logout"
USERS_ME = "/users/me"
DOC = "doc"
OPENAPI = "openapi"
FAVICON = "favicon"
