"""All api endpints related to fetch aws S3."""
from constants.params.s3 import S3_FILE_PATH, LOCAL_FILE_PATH
S3_STATUS = "/status"
S3_PREFIX = "/s3"
CREATE_BUCKET = "/create-bucket/"
UPLOAD_FILES = "/upload-files/"
LIST_ALL_BUCKETS = "/list-all-buckets"
GET_ENTERPRISE_BUCKET_NAME = "/get-enterprise-bucket-name"
GET_S3_FILE = "/browse-s3-file"
DOWNLOAD_S3_FILE = f"/download-s3-file/{S3_FILE_PATH}"
GET_PROJECT_ALL_OBJECTS = "/get-projects-objects"
BROWSE_S3_FILE_PATH = f"/browse-s3-file/{S3_FILE_PATH}"
DOWNLOAD_S3_FILE_LOCAL_CUSTOM_PATH = f"/download-s3-file/{S3_FILE_PATH}/{LOCAL_FILE_PATH}"
GENERATE_UPLOAD_PRE_SIGNED_S3_URL = "/generate-upload-photos-url"
